/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ak47.glb -t -T 
Files: ak47.glb [154.67KB] > /Users/fant/work/personal-blog/public/models/ak47-transformed.glb [16.29KB] (89%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    GUN_Material_0: THREE.Mesh
  }
  materials: {
    ['Material.007']: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export const Ak47Model = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/models-transformed/ak47-transformed.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.GUN_Material_0.geometry} material={materials['Material.007']} rotation={[-Math.PI, -Math.PI / 2, 0]} />
    </group>
  )
})

useGLTF.preload('/models-transformed/ak47-transformed.glb')
