/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 controller.glb -t -T 
Files: controller.glb [156.86KB] > /Users/fant/work/personal-blog/public/models/controller-transformed.glb [11.28KB] (93%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    playstation: THREE.Mesh
  }
  materials: {
    Dualshock_Blue: THREE.MeshBasicMaterial
  }
  animations: any[]
}

export const ControllerModel = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/models-transformed/controller-transformed.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.playstation.geometry} material={materials.Dualshock_Blue}  rotation={[-1.738, 0.006, 3.111]}  />
    </group>
  )
})

useGLTF.preload('/models-transformed/controller-transformed.glb')
