/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 crash.glb -t -T 
Files: crash.glb [41.62KB] > /Users/fant/work/personal-blog/public/models/crash-transformed.glb [11.97KB] (71%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_0010: THREE.Mesh
    Object_0010_1: THREE.Mesh
    Object_0010_2: THREE.Mesh
  }
  materials: {
    back: THREE.MeshStandardMaterial
    color_pallete: THREE.MeshStandardMaterial
    shoes: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export const CrashModel = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/models-transformed/crash-transformed.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <group  rotation={[-Math.PI / 2, 0, 0]} >
        <mesh geometry={nodes.Object_0010.geometry} material={materials.back} />
        <mesh geometry={nodes.Object_0010_1.geometry} material={materials.color_pallete} />
        <mesh geometry={nodes.Object_0010_2.geometry} material={materials.shoes} />
      </group>
    </group>
  )
})

useGLTF.preload('/models-transformed/crash-transformed.glb')
