/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 daftpunk.glb -t -T 
Files: daftpunk.glb [36.52KB] > /Users/fant/work/personal-blog/public/models/daftpunk-transformed.glb [5.96KB] (84%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    daftpunk: THREE.Mesh
  }
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export const DaftpunkModel = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/models-transformed/daftpunk-transformed.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.daftpunk.geometry} material={materials['Material.003']}   />
    </group>
  )
})

useGLTF.preload('/models-transformed/daftpunk-transformed.glb')
