/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 deadmau5.glb -t -T 
Files: deadmau5.glb [33.6KB] > /Users/fant/work/personal-blog/public/models/deadmau5-transformed.glb [6.49KB] (81%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    deadmau5: THREE.Mesh
  }
  materials: {
    color_12568524: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export const Deadmau5Model = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/models-transformed/deadmau5-transformed.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.deadmau5.geometry} material={materials.color_12568524}  rotation={[-Math.PI, 0, 0]}  />
    </group>
  )
})

useGLTF.preload('/models-transformed/deadmau5-transformed.glb')
