/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 dexter.glb -t -T 
Files: dexter.glb [130.6KB] > /Users/fant/work/personal-blog/public/models/dexter-transformed.glb [39.56KB] (70%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_0003: THREE.Mesh
    Object_0003_1: THREE.Mesh
    Object_0003_2: THREE.Mesh
    Object_0003_3: THREE.Mesh
    Object_0003_4: THREE.Mesh
    Object_0003_5: THREE.Mesh
    Object_0003_6: THREE.Mesh
    Object_0003_7: THREE.Mesh
    Object_0003_8: THREE.Mesh
    Object_0003_9: THREE.Mesh
  }
  materials: {
    Material__103: THREE.MeshStandardMaterial
    Material__53: THREE.MeshStandardMaterial
    Material__68: THREE.MeshStandardMaterial
    Material__71: THREE.MeshStandardMaterial
    Material__89: THREE.MeshStandardMaterial
    Material__57: THREE.MeshStandardMaterial
    Material__69: THREE.MeshStandardMaterial
    Material__56: THREE.MeshStandardMaterial
    Material__52: THREE.MeshStandardMaterial
    Material__70: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export const DexterModel = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/models-transformed/dexter-transformed.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <group  rotation={[-Math.PI / 2, 0, 0]} >
        <mesh geometry={nodes.Object_0003.geometry} material={materials.Material__103} />
        <mesh geometry={nodes.Object_0003_1.geometry} material={materials.Material__53} />
        <mesh geometry={nodes.Object_0003_2.geometry} material={materials.Material__68} />
        <mesh geometry={nodes.Object_0003_3.geometry} material={materials.Material__71} />
        <mesh geometry={nodes.Object_0003_4.geometry} material={materials.Material__89} />
        <mesh geometry={nodes.Object_0003_5.geometry} material={materials.Material__57} />
        <mesh geometry={nodes.Object_0003_6.geometry} material={materials.Material__69} />
        <mesh geometry={nodes.Object_0003_7.geometry} material={materials.Material__56} />
        <mesh geometry={nodes.Object_0003_8.geometry} material={materials.Material__52} />
        <mesh geometry={nodes.Object_0003_9.geometry} material={materials.Material__70} />
      </group>
    </group>
  )
})

useGLTF.preload('/models-transformed/dexter-transformed.glb')
