/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 halo.glb -t -T 
Files: halo.glb [1.4MB] > /Users/fant/work/personal-blog/public/models/halo-transformed.glb [96.46KB] (93%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    halo: THREE.Mesh
  }
  materials: {
    lambert3: THREE.MeshPhysicalMaterial
  }
  animations: any[]
}

export const HaloModel = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/models-transformed/halo-transformed.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.halo.geometry} material={materials.lambert3}  rotation={[Math.PI / 2, 0, -Math.PI / 2]}  />
    </group>
  )
})

useGLTF.preload('/models-transformed/halo-transformed.glb')
