/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 kanye.glb -t -T 
Files: kanye.glb [1.23MB] > /Users/fant/work/personal-blog/public/models/kanye-transformed.glb [54.33KB] (96%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    kanye: THREE.Mesh
  }
  materials: {
    ['03_-_Default']: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export const KanyeModel = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/models-transformed/kanye-transformed.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.kanye.geometry} material={materials['03_-_Default']}  rotation={[-Math.PI / 2, 0, 0]}  />
    </group>
  )
})

useGLTF.preload('/models-transformed/kanye-transformed.glb')
