/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 minecraft.glb -t -T 
Files: minecraft.glb [62.97KB] > /Users/fant/work/personal-blog/public/models/minecraft-transformed.glb [5.85KB] (91%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    minecraft: THREE.Mesh
  }
  materials: {
    ['48bab62c9c1a63f03df645b9dfffd321']: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export const MinecraftModel = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/models-transformed/minecraft-transformed.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.minecraft.geometry} material={materials['48bab62c9c1a63f03df645b9dfffd321']}  rotation={[0.014, 0, 0]}  />
    </group>
  )
})

useGLTF.preload('/models-transformed/minecraft-transformed.glb')
