/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 rayman.glb -t -T 
Files: rayman.glb [237.87KB] > /Users/fant/work/personal-blog/public/models/rayman-transformed.glb [23.72KB] (90%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    rayman: THREE.Mesh
  }
  materials: {
    Material_53: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export const RaymanModel = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/models-transformed/rayman-transformed.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.rayman.geometry} material={materials.Material_53}  rotation={[-Math.PI / 2, 0, 0]}  />
    </group>
  )
})

useGLTF.preload('/models-transformed/rayman-transformed.glb')
