/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ../../public/models/snake.glb -t -T 
Files: ../../public/models/snake.glb [18.07KB] > /Users/fant/work/personal-blog/src/components/snake-transformed.glb [11.72KB] (35%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_15: THREE.Mesh
    Object_15_1: THREE.Mesh
    Object_15_2: THREE.Mesh
    Object_15_3: THREE.Mesh
    Object_15_4: THREE.Mesh
    Object_15_5: THREE.Mesh
    Object_15_6: THREE.Mesh
    Object_15_7: THREE.Mesh
  }
  materials: {
    Head_Back: THREE.MeshStandardMaterial
    Ear_Sides: THREE.MeshStandardMaterial
    Ear_Fronts: THREE.MeshStandardMaterial
    Head_Front: THREE.MeshStandardMaterial
    Head_Sides: THREE.MeshStandardMaterial
    Neck_Back: THREE.MeshStandardMaterial
    Neck_Front: THREE.MeshStandardMaterial
    Head: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export const SnakeModel = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/models-transformed/snake-transformed.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <group  rotation={[-Math.PI / 2, 0, 0]} >
        <mesh geometry={nodes.Object_15.geometry} material={materials.Head_Back} />
        <mesh geometry={nodes.Object_15_1.geometry} material={materials.Ear_Sides} />
        <mesh geometry={nodes.Object_15_2.geometry} material={materials.Ear_Fronts} />
        <mesh geometry={nodes.Object_15_3.geometry} material={materials.Head_Front} />
        <mesh geometry={nodes.Object_15_4.geometry} material={materials.Head_Sides} />
        <mesh geometry={nodes.Object_15_5.geometry} material={materials.Neck_Back} />
        <mesh geometry={nodes.Object_15_6.geometry} material={materials.Neck_Front} />
        <mesh geometry={nodes.Object_15_7.geometry} material={materials.Head} />
      </group>
    </group>
  )
})

useGLTF.preload('/models-transformed/snake-transformed.glb')
