/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 steve.glb -t -T 
Files: steve.glb [7.77KB] > /Users/fant/work/personal-blog/public/models/steve-transformed.glb [2.92KB] (62%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    steve: THREE.Mesh
  }
  materials: {
    ['02_-_Default']: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export const SteveModel = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/models-transformed/steve-transformed.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.steve.geometry} material={materials['02_-_Default']}  rotation={[-Math.PI / 2, 0, 0]}  />
    </group>
  )
})

useGLTF.preload('/models-transformed/steve-transformed.glb')
