/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 terraria.glb -t -T 
Files: terraria.glb [10.13KB] > /Users/fant/work/personal-blog/public/models/terraria-transformed.glb [3.5KB] (65%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    terraria: THREE.Mesh
  }
  materials: {
    material_0: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export const TerrariaModel = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/models-transformed/terraria-transformed.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.terraria.geometry} material={materials.material_0}  scale={[15.076, 15.076, 13.568]} />
    </group>
  )
})

useGLTF.preload('/models-transformed/terraria-transformed.glb')
