/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 zombie.glb -t -T 
Files: zombie.glb [11.58KB] > /Users/fant/work/personal-blog/public/models/zombie-transformed.glb [8.06KB] (30%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_5003: THREE.Mesh
    Object_5003_1: THREE.Mesh
    Object_5003_2: THREE.Mesh
  }
  materials: {
    ['material_0.001']: THREE.MeshStandardMaterial
    material_1: THREE.MeshStandardMaterial
    material_2: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export const ZombieModel = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/models-transformed/zombie-transformed.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <group  rotation={[Math.PI, 0, Math.PI]} >
        <mesh geometry={nodes.Object_5003.geometry} material={materials['material_0.001']} />
        <mesh geometry={nodes.Object_5003_1.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Object_5003_2.geometry} material={materials.material_2} />
      </group>
    </group>
  )
})

useGLTF.preload('/models-transformed/zombie-transformed.glb')
